name: Release cliq

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'new semantic version'
        required: true
        default: 'v0.0.0'

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate `CHANGELOG.md`
        uses: orhun/git-cliff-action@v4
        with:
          config: cliff.toml
          args: --tag ${{ github.event.inputs.version }}
        env:
          OUTPUT: CHANGELOG.md

      - name: Commit and tag
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          set +e
          git add CHANGELOG.md
          git commit -m "chore(release): prepare for ${{ github.event.inputs.version }}"
          git tag -a ${{ github.event.inputs.version }} -m "${{ github.event.inputs.version }}"
          git push https://${{ secrets.GH_TOKEN }}@github.com/adamperkowski/cliq.git HEAD:refs/heads/main --follow-tags

  release:
    runs-on: ubuntu-latest
    needs: tag

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.version }}

      - name: Prepare files
        run: |
          VERSION=${{ github.event.inputs.version }} make package

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.version }}
          name: ${{ github.event.inputs.version }}
          body: |
            cliq ${{ github.event.inputs.version }}
            ## Major Changes
          append_body: true
          files: |
            cliq-${{ github.event.inputs.version }}.tar.gz
            cliq-${{ github.event.inputs.version }}.zip
          prerelease: ${{ contains(github.event.inputs.version, '-') }}
